-- V1__init.sql
-- Initiales Schema für whatsapp-gateway.
--   studio_config : Pro Studio die WABA-/Phone-Number-Konfiguration + (verschlüsseltes) Token.
--   inbound_event : Idempotenz-/Audit-Log für eingehende Messages und Status-Updates.

CREATE TABLE IF NOT EXISTS studio_config (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_id            VARCHAR(100) NOT NULL,
    waba_id              VARCHAR(50)  NOT NULL,
    phone_number_id      VARCHAR(50)  NOT NULL,
    display_phone_number VARCHAR(30),
    access_token         TEXT         NOT NULL,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_studio_config_studio_id       UNIQUE (studio_id),
    CONSTRAINT uq_studio_config_phone_number_id UNIQUE (phone_number_id)
);

CREATE INDEX IF NOT EXISTS idx_studio_config_phone_number_id
    ON studio_config (phone_number_id);

CREATE TABLE IF NOT EXISTS inbound_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_id         VARCHAR(255) NOT NULL,
    phone_number_id VARCHAR(50),
    type            VARCHAR(20)  NOT NULL,
    payload         JSONB,
    received_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_inbound_event_meta_id UNIQUE (meta_id)
);

CREATE INDEX IF NOT EXISTS idx_inbound_event_phone_number_id
    ON inbound_event (phone_number_id);
